
TESTS=./riscv-tests/isa/rv32ui-p-add \
	./riscv-tests/isa/rv32ui-p-addi \
	./riscv-tests/isa/rv32ui-p-and \
	./riscv-tests/isa/rv32ui-p-andi \
	./riscv-tests/isa/rv32ui-p-auipc \
	./riscv-tests/isa/rv32ui-p-beq \
	./riscv-tests/isa/rv32ui-p-bge \
	./riscv-tests/isa/rv32ui-p-bgeu \
	./riscv-tests/isa/rv32ui-p-blt \
	./riscv-tests/isa/rv32ui-p-bltu \
	./riscv-tests/isa/rv32ui-p-bne \
	./riscv-tests/isa/rv32ui-p-fence_i \
	./riscv-tests/isa/rv32ui-p-jal \
	./riscv-tests/isa/rv32ui-p-jalr \
	./riscv-tests/isa/rv32ui-p-lb \
	./riscv-tests/isa/rv32ui-p-lbu \
	./riscv-tests/isa/rv32ui-p-ld_st \
	./riscv-tests/isa/rv32ui-p-lh \
	./riscv-tests/isa/rv32ui-p-lhu \
	./riscv-tests/isa/rv32ui-p-lui \
	./riscv-tests/isa/rv32ui-p-lw \
	./riscv-tests/isa/rv32ui-p-ma_data \
	./riscv-tests/isa/rv32ui-p-or \
	./riscv-tests/isa/rv32ui-p-ori \
	./riscv-tests/isa/rv32ui-p-sb \
	./riscv-tests/isa/rv32ui-p-sh \
	./riscv-tests/isa/rv32ui-p-simple \
	./riscv-tests/isa/rv32ui-p-sll \
	./riscv-tests/isa/rv32ui-p-slli \
	./riscv-tests/isa/rv32ui-p-slt \
	./riscv-tests/isa/rv32ui-p-slti \
	./riscv-tests/isa/rv32ui-p-sltiu \
	./riscv-tests/isa/rv32ui-p-sltu \
	./riscv-tests/isa/rv32ui-p-sra \
	./riscv-tests/isa/rv32ui-p-srai \
	./riscv-tests/isa/rv32ui-p-srl \
	./riscv-tests/isa/rv32ui-p-srli \
	./riscv-tests/isa/rv32ui-p-st_ld \
	./riscv-tests/isa/rv32ui-p-sub \
	./riscv-tests/isa/rv32ui-p-sw \
	./riscv-tests/isa/rv32ui-p-xor \
	./riscv-tests/isa/rv32ui-p-xori \
	./riscv-tests/isa/rv32ui-v-add \
	./riscv-tests/isa/rv32ui-v-addi \
	./riscv-tests/isa/rv32ui-v-and \
	./riscv-tests/isa/rv32ui-v-andi \
	./riscv-tests/isa/rv32ui-v-auipc \
	./riscv-tests/isa/rv32ui-v-beq \
	./riscv-tests/isa/rv32ui-v-bge \
	./riscv-tests/isa/rv32ui-v-bgeu \
	./riscv-tests/isa/rv32ui-v-blt \
	./riscv-tests/isa/rv32ui-v-bltu \
	./riscv-tests/isa/rv32ui-v-bne \
	./riscv-tests/isa/rv32ui-v-fence_i \
	./riscv-tests/isa/rv32ui-v-jal \
	./riscv-tests/isa/rv32ui-v-jalr \
	./riscv-tests/isa/rv32ui-v-lb \
	./riscv-tests/isa/rv32ui-v-lbu \
	./riscv-tests/isa/rv32ui-v-ld_st \
	./riscv-tests/isa/rv32ui-v-lh \
	./riscv-tests/isa/rv32ui-v-lhu \
	./riscv-tests/isa/rv32ui-v-lui \
	./riscv-tests/isa/rv32ui-v-lw \
	./riscv-tests/isa/rv32ui-v-ma_data \
	./riscv-tests/isa/rv32ui-v-or \
	./riscv-tests/isa/rv32ui-v-ori \
	./riscv-tests/isa/rv32ui-v-sb \
	./riscv-tests/isa/rv32ui-v-sh \
	./riscv-tests/isa/rv32ui-v-simple \
	./riscv-tests/isa/rv32ui-v-sll \
	./riscv-tests/isa/rv32ui-v-slli \
	./riscv-tests/isa/rv32ui-v-slt \
	./riscv-tests/isa/rv32ui-v-slti \
	./riscv-tests/isa/rv32ui-v-sltiu \
	./riscv-tests/isa/rv32ui-v-sltu \
	./riscv-tests/isa/rv32ui-v-sra \
	./riscv-tests/isa/rv32ui-v-srai \
	./riscv-tests/isa/rv32ui-v-srl \
	./riscv-tests/isa/rv32ui-v-srli \
	./riscv-tests/isa/rv32ui-v-st_ld \
	./riscv-tests/isa/rv32ui-v-sub \
	./riscv-tests/isa/rv32ui-v-sw \
	./riscv-tests/isa/rv32ui-v-xor \
	./riscv-tests/isa/rv32ui-v-xori

tests: $(TESTS)

./riscv-tests/isa/%: Makefile
	bash src/test.sh $@
